# SITE CONFIGURATION
baseurl: ""
url: "https://kyleshores.com"

# THEME-SPECIFIC CONFIGURATION
title: Kyle Shores # site's title
description: "A personal blog and portfolio site" # used by search engines
avatar: assets/img/me.webp # Empty for no avatar in navbar
favicon: assets/favicon.ico # Icon displayed in the tab

# Header and footer text
header_text: Kyle Shores
header_feature_image: assets/img/header/stormy-atlantic-background.webp
header_feature_image_responsive: true
footer_text: >
  © 2024 Kyle Shores

# Blog
excerpt: true # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png # A bit transparent for color posts.

future: true

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true # Enable if using math markup
mermaid: default # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics: G-Q1275HH65D
cookie_consent: true # To respect the usage of cookies
color_theme: auto # auto, dark or light

# Comments options
comments:
  disqus_shortname: kyleshores-com-1
  cusdis_app_id: # Your cusdis data-app-id
  utterances: # Enable by filling below information. For more info, go to https://utteranc.es
    repo: # your public comments repository (e.g. owner/repo)
    issue-term: # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude:
  [
    ".jekyll-cache",
    ".jekyll-metadata",
    ".idea",
    "vendor/*",
    "assets/node_modules/*",
  ]