name: Projects test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  game_of_life:
    runs-on: ${{ matrix.os }}

    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    # setup node
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
      
      - name: Install dependencies
        run: |
          cd assets/js/projects/game_of_life
          npm install

      - name: Run tests
        run: |
          cd assets/js/projects/game_of_life
          npm test