name: Projects test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  game_of_life:
    matrix:
      os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    # setup node
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: 
          cd assets/js/projects/game_of_life
          npm install

      - name: Run tests
        run: npm test